version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  # در صورت نیاز می‌تونی backend و mongo رو هم اینجا اضافه کنی
  # backend:
  #   ...

networks:
  app-network:
    driver: bridge
