version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"   # فرانت روی پورت 5173 بیرون بازه
    volumes:
      - ./frontend:/app
    command: npm run dev
    environment:
      - HOST=0.0.0.0
      - PORT=5173
    restart: always

  backend:
    build: ./backend
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    command: npm start
    environment:
      - MONGO_URL=mongodb://mongo:27017/menue
    restart: always

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
