services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev
    #restart: always

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: npm start
    depends_on:
      - mongo
    environment:
    - MONGO_URL=mongodb://localhost:27017/menue
    #restart: always

  mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
