version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: always
    environment:
      - MONGO_URL=mongodb://host.docker.internal:27017/menue  # یا اگر لینوکس هست: mongodb://localhost:27017/menue
