version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: npm start
    environment:
      # - MONGO_URL=mongodb://host.docker.internal:27017/menue  # اگر روی ویندوز یا مک هستی
      - MONGO_URL=mongodb://localhost:27017/menue            # اگر روی لینوکس هستی
    restart: always
