version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: npm start
    environment:
      - MONGO_URL=mongodb://localhost:27017/menue
    restart: always
