name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 171.22.26.36
          username: root
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            set -e
            if [ ! -d "/opt/app" ]; then
              echo "First time setup: Cloning repo..."
              git clone https://github.com/pmtking/menue_final.git /opt/app
            else
              echo "Repo exists. Resetting local changes and pulling latest..."
              cd /opt/app
              git reset --hard
              git pull origin main
            fi

            cd /opt/app
            echo "Stopping existing containers..."
            docker compose down

            echo "Starting containers with build..."
            docker compose up -d --build

            echo "Deployment finished."
